### ISSUE TITLE
Tests on main are failing

### ISSUE THREAD

**Issue by HarmvZ** [DIAGNijmegen/rse-gcapi#155]
Integration tests are failing. 
```
tests/test_models.py ......                                                                                     [  4%]
tests/test_async_transports.py ....                                                                             [  7%]
tests/async_client_hybrid_tests.py ...                                                                          [  9%]
tests/test_retries.py ........                                                                                  [ 15%]
tests/integration_tests.py EEEEEEEEEEEEEEEEEEEEEE.EEEEEEEEEEEEEEEE                                              [ 43%]
tests/async_integration_tests.py EEEEEEEEEEEEEEEEEEEEEEEEE.EEEEEEEEEEEEE                                        [ 71%]
tests/test_transports.py ....                                                                                   [ 74%]
tests/test_gcapi.py ...................................                                                         [100%]
```

Seemingly something is going wrong with creation of the development fixtures of GC. I think this is the cause:

```
Traceback (most recent call last):
  File "/opt/poetry/.venv/lib/python3.11/site-packages/django_extensions/management/commands/runscript.py", line 204, in my_import
    t = importlib.import_module(full_module_path)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/scripts/development_fixtures.py", line 15, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
CommandError: An error has occurred running scripts. See errors above.
make: *** [Makefile:101: development_fixtures] Error 1
```

**Comment by jmsmkn** [comment]
Going to have a go at updating the models now.

**Comment by jmsmkn** [comment]
The model generation is fixed. Going to deploy GC with the latest models first before making a PR.
